apiVersion: batch/v1
kind: CronJob
metadata:
  name: test
  namespace: testkube
  annotations:
    test: kube
  ownerReferences:
    - apiVersion: tests.testkube.io/v3
      kind: Test
      name: secret-list
      uid: 304a7965-78ec-4f8b-9035-f3c0977d910c
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox:1.28
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
