apiVersion: tests.testkube.io/v3
kind: Test
metadata:
  name: mv-test
  namespace: testkube
spec:
spec:
  type: maven/test
  content:
    type: git
    repository:
      type: git
      uri: https://github.com/blap/e2e-tests
      branch: develop
      path: hello-maven
