apiVersion: v1
kind: Pod
metadata:
  name: "{{ .Name }}"
  namespace: {{ .Namespace }}
  ownerReferences:
  - apiVersion: batch/v1
    kind: job
    name: {{ .JobName }}
    uid: {{ .JobUID }}
  labels:
    distributed: jmeter
