apiVersion: v1
kind: Pod
metadata:
  name: "jmeterd-example-4-slave-2-6560f627158ac5673ffce08f"
  namespace: testkube
  ownerReferences:
  - apiVersion: batch/v1
    kind: job
    name: 6560f627158ac5673ffce08f
    uid: b7501c04-e0c4-44c9-8f5c-39a0db95ddf6
spec:
  initContainers:
  - name: init
    image: kubeshop/testkube-init-executor:9e6032b
    imagePullPolicy: IfNotPresent
    command:
    - "/bin/runner"
    - '{\"id\":\"6560f627158ac5673ffce08f\",\"testName\":\"jmeterd-example\",\"testNamespace\":\"testkube\",\"testType\":\"jmeterd/test\",\"name\":\"jmeterd-example-4\",\"number\":4,\"command\":[\"\\u003centryPoint\\u003e\"],\"args\":[\"-n\",\"-j\",\"/data/output/jmeter.log\",\"-t\",\"/data/repo/contrib/executor/jmeterd/examples/gitflow/jmeter-properties-external.jmx\",\"-l\",\"/data/output/report.jtl\",\"-e\",\"-o\",\"/data/output/report\",\"\\u003cenvVars\\u003e\",\"-GJMETER_UC1_NBUSERS=5\"],\"variables\":{\"DATA_CONFIG\":{\"name\":\"DATA_CONFIG\",\"value\":\"/data/repo/contrib/executor/jmeterd/examples/gitflow\",\"type\":\"basic\"}},\"content\":{\"type\":\"git\",\"repository\":{\"type\":\"git\",\"uri\":\"https://github.com/kubeshop/testkube\",\"branch\":\"develop\",\"path\":\"contrib/executor/jmeterd/examples/gitflow\"}},\"startTime\":\"2023-11-24T19:14:47.851338242Z\",\"endTime\":\"0001-01-01T00:00:00Z\",\"executionResult\":{\"status\":\"running\"},\"labels\":{\"executor\":\"jmeterd-executor\",\"test-type\":\"jmeterd-test\"},\"bucketName\":\"24523b79-229c-4c58-bc89-43c1f19e24f4\",\"runningContext\":{\"type\":\"user-cli\"},\"slavePodRequest\":{\"resources\":{\"requests\":{\"cpu\":\"512m\",\"memory\":\"512Mi\"},\"limits\":{\"cpu\":\"1024m\",\"memory\":\"1024Mi\"}}}}'
    volumeMounts:
    - name: data-volume
      mountPath: /data
  containers:
  - name: main
    image: kubeshop/testkube-jmeterd-slave:9e6032b
    imagePullPolicy: IfNotPresent
    ports:
    - name: server-port
      containerPort: 1099
    - name: local-port
      containerPort: 60001
    livenessProbe:
      tcpSocket:
        port: 1099
      failureThreshold: 3
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 1
    readinessProbe:
      tcpSocket:
        port: 1099
      failureThreshold: 3
      initialDelaySeconds: 10
      periodSeconds: 5
      timeoutSeconds: 1
    resources:
      limits:
        cpu: 1024m
        memory: 1024M
      requests:
        cpu: 512m
        memory: 512Mi
    volumeMounts:
    - name: data-volume
      mountPath: /data
  volumes:
  - name: data-volume
    emptyDir: {}
  restartPolicy: Always
  serviceAccountName: testkube-api-server-tests-job
