apiVersion: batch/v1
kind: Job
spec:
  template:
    spec:
      containers:
      - name: {{ .Name }}-scraper
        image: {{ .ScraperImage }}
        imagePullPolicy: Always
        command:
          - "/bin/runner"
          - '{{ .Jsn }}'
        {{- if .ArtifactRequest }}
          {{- if .ArtifactRequest.VolumeMountPath }}
        volumeMounts:
          - name: artifact-volume
            mountPath: {{ .ArtifactRequest.VolumeMountPath }}
          {{- end }}
        {{- end }}
        resources:
          limits:
            memory: 512Mi
