apiVersion: v1
kind: Secret
metadata:
  name: secret-visibility
  namespace: testkube
  labels:
    visibility: testkube
type: Opaque
data:
  FIRST_VAR: MQ==
  SECOND_VAR: OGM0ZThlYzU0NzI2YzA4MTQwMjUyNWM4MzRkNGQwOTFkODBjODAzNw==
  apiUrl: aHR0cHM6Ly9nb29nbGUuY29t
  apiPath: aGVhbHRo
