apiVersion: tests.testkube.io/v3
kind: Test
metadata:
  name: container-executor-curl-smoke
  namespace: testkube
  labels:
    core-tests: executors
spec:
  type: container-executor-curl/test
  executionRequest:
    args:
    - $(URL)
    variables:
      URL:
        name: URL
        value: https://testkube.kubeshop.io/
