apiVersion: tests.testkube.io/v2
kind: TestSuite
metadata:
  name: testsuite-old
  namespace: testkube
spec:
  steps: 
    - delay: 
        duration: 1000
    - execute: 
        namespace: testkube 
        name: sanity
