apiVersion: tests.testkube.io/v3
kind: Test
metadata:
  name: k6-dwwd-test
  namespace: testkube
spec:
  type: k6/script
  content:
    type: git-dir
    repository:
      type: git
      uri: https://github.com/kubeshop/testkube.git
      branch: main
  executionRequest:
    args:
      - test/k6/executor-tests/k6-smoke-test-without-envs.js
