apiVersion: tests.testkube.io/v3
kind: Test
metadata:
  name: cs-env-tmp
  namespace: testkube
spec:
  type: postman/collection
  content:
    type: string
    data: "{\n\t\"info\": {\n\t\t\"_postman_id\": \"3d9a6be2-bd3e-4cf7-89ca-354103aab4a7\",\n\t\t\"name\": \"Health\",\n\t\t\"schema\": \"https://schema.getpostman.com/json/collection/v2.1.0/collection.json\"\n\t},\n\t\"item\": [\n\t\t{\n\t\t\t\"name\": \"Health\",\n\t\t\t\"event\": [\n\t\t\t\t{\n\t\t\t\t\t\"listen\": \"test\",\n\t\t\t\t\t\"script\": {\n\t\t\t\t\t\t\"exec\": [\n\t\t\t\t\t\t\t\"pm.test(\\\"Status code is 200\\\", function () {\",\n\t\t\t\t\t\t\t\"    pm.response.to.have.status(200);\",\n\t\t\t\t\t\t\t\"});\"\n\t\t\t\t\t\t],\n\t\t\t\t\t\t\"type\": \"text/javascript\"\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t],\n\t\t\t\"request\": {\n\t\t\t\t\"method\": \"GET\",\n\t\t\t\t\"header\": [],\n\t\t\t\t\"url\": {\n\t\t\t\t\t\"raw\": \"{{URI}}/health\",\n\t\t\t\t\t\"host\": [\n\t\t\t\t\t\t\"{{URI}}\"\n\t\t\t\t\t],\n\t\t\t\t\t\"path\": [\n\t\t\t\t\t\t\"health\"\n\t\t\t\t\t]\n\t\t\t\t}\n\t\t\t},\n\t\t\t\"response\": []\n\t\t}\n\t],\n\t\"event\": [\n\t\t{\n\t\t\t\"listen\": \"prerequest\",\n\t\t\t\"script\": {\n\t\t\t\t\"type\": \"text/javascript\",\n\t\t\t\t\"exec\": [\n\t\t\t\t\t\"\"\n\t\t\t\t]\n\t\t\t}\n\t\t},\n\t\t{\n\t\t\t\"listen\": \"test\",\n\t\t\t\"script\": {\n\t\t\t\t\"type\": \"text/javascript\",\n\t\t\t\t\"exec\": [\n\t\t\t\t\t\"\"\n\t\t\t\t]\n\t\t\t}\n\t\t}\n\t],\n\t\"variable\": [\n\t\t{\n\t\t\t\"key\": \"URI\",\n\t\t\t\"value\": \"http://localhost:8080\"\n\t\t}\n\t]\n}"
  executionRequest:
    envConfigMaps:
    - mount: true
      mountPath: /data/map1
      mapToVariables: false
      reference: 
        name: map1
    - mount: false
      mapToVariables: true
      reference: 
        name: map2
    envSecrets:
    - mount: true
      mountPath: /data/secret3
      mapToVariables: true
      reference: 
        name: secret3

