apiVersion: tests.testkube.io/v1
kind: TestTrigger
metadata:
  name: testtrigger-1
  namespace: testkube
spec:
  resource: deployment
  resourceSelector:
    labelSelector:
      matchLabels:
       app: nginx
  event: created
  action: run
  execution: test
  concurrencyPolicy: replace
  testSelector:
    name: cypress-multi-files-test
    namespace: testkube
