apiVersion: tests.testkube.io/v1
kind: TestTrigger
metadata:
  name: testtrigger-conditions
  namespace: testkube
spec:
  resource: deployment
  resourceSelector:
    labelSelector:
      matchLabels:
       app: nginx
  event: created
  conditionSpec:
    timeout: 100
    delay: 2
    conditions:
    - type: Progressing
      status: "True"
      reason: NewReplicaSetAvailable
      ttl: 60
    - type: Available
      status: "True"
  action: run
  execution: test
  testSelector:
    name: jmeter-executor-smoke
    namespace: testkube
