apiVersion: tests.testkube.io/v1
kind: TestTrigger
metadata:
  name: testtrigger-pod
  namespace: testkube
spec:
  resource: pod
  resourceSelector:
    labelSelector:
      matchLabels:
       app: nginx
  event: created
  probeSpec:
    timeout: 50
    delay: 1
    probes:
    - port: 80
  action: run
  execution: test
  concurrencyPolicy: allow
  testSelector:
    name: curl-dots
    namespace: testkube
