apiVersion: tests.testkube.io/v1
kind: TestTrigger
metadata:
  name: testtrigger-probes
  namespace: testkube
spec:
  resource: deployment
  resourceSelector:
    labelSelector:
      matchLabels:
       app: nginx
  event: created
  probeSpec:
    timeout: 50
    delay: 1
    probes:
    - scheme: http
      host: testkube-api-server.testkube.svc.cluster.local
      path: /health
      port: 8088
      headers:
        X-Token: "12345"
    - scheme: https
      host: testkube.io
  action: run
  execution: test
  testSelector:
    name: k6-executor-smoke
    namespace: testkube
