apiVersion: tests.testkube.io/v1
kind: TestTrigger
metadata:
  name: testtrigger-configmap
  namespace: testkube
spec:
  resource: configmap
  resourceSelector:
    labelSelector:
      matchLabels:
       testkube.io/tier: backend
  event: created
  action: run
  execution: test
  testSelector:
    name: cli-test
    namespace: testkube
