apiVersion: v1
kind: PersistentVolume
metadata:
  name: artifact-volume
spec:
  storageClassName: standard
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/opt/volume/testkube"
